export const allProducts = [
    {
      id: 1,
      name: "Nendoroid Tanjiro Kamado",
      price: 45.99,
      image: "https://www.goodsmileus.com/images/product/image_1945.png",
      description: "Figura Nendoroid de Tanjiro Kamado de 'Demon Slayer'. Incluye accesorios y caras intercambiables.",
      stock: 10,
      inStock: true,
      category: "Figuras",
      genre: "Anime",
      preOrder: false,
    },
    {
      id: 2,
      name: "Base para Nendoroid (Transparente)",
      price: 9.99,
      image: "https://www.goodsmileus.com/images/product/image_3001.png",
      description: "Base de repuesto para Nendoroids. Transparente y compatible con la mayoría de las figuras.",
      stock: 20,
      inStock: true,
      category: "Accesorios",
      genre: "General",
      preOrder: false,
    },
    {
      id: 3,
      name: "Nendoroid Link - Breath of the Wild",
      price: 49.99,
      image: "https://www.goodsmileus.com/images/product/image_2305.png",
      description: "Figura Nendoroid de Link de 'The Legend of Zelda: Breath of the Wild'. Viene con su arco, espada y escudo.",
      stock: 8,
      inStock: true,
      category: "Figuras",
      genre: "Videojuegos",
      preOrder: false,
    },
    {
      id: 4,
      name: "Nendoroid Miku Hatsune V4X",
      price: 52.99,
      image: "https://www.goodsmileus.com/images/product/image_1892.png",
      description: "Figura Nendoroid de Hatsune Miku versión V4X. Incluye micrófono y poses dinámicas.",
      stock: 15,
      inStock: true,
      category: "Figuras",
      genre: "Vocaloid",
      preOrder: false,
    },
    {
      id: 5,
      name: "Set de Manos Extras para Nendoroids",
      price: 12.99,
      image: "https://www.goodsmileus.com/images/product/image_3015.png",
      description: "Pack de manos adicionales con diferentes poses para personalizar tu Nendoroid.",
      stock: 30,
      inStock: true,
      category: "Accesorios",
      genre: "General",
      preOrder: false,
    },
    {
      id: 6,
      name: "Nendoroid Gojo Satoru",
      price: 50.99,
      image: "https://www.goodsmileus.com/images/product/image_2857.png",
      description: "Figura Nendoroid de Gojo Satoru de 'Jujutsu Kaisen'. Incluye su máscara y expresiones intercambiables.",
      stock: 5,
      inStock: true,
      category: "Figuras",
      genre: "Anime",
      preOrder: true,
    },
    {
      id: 7,
      name: "Nendoroid Megumin",
      price: 47.99,
      image: "https://www.goodsmileus.com/images/product/image_1678.png",
      description: "Figura Nendoroid de Megumin de 'Konosuba'. Viene con su báculo y efectos de explosión.",
      stock: 0,
      inStock: false,
      category: "Figuras",
      genre: "Anime",
      preOrder: false,
    },
    {
      id: 8,
      name: "Fondo Temático - Noche Estrellada",
      price: 14.99,
      image: "https://www.goodsmileus.com/images/product/image_3020.png",
      description: "Fondo decorativo para exhibir Nendoroids. Tema: Noche estrellada.",
      stock: 12,
      inStock: true,
      category: "Accesorios",
      genre: "General",
      preOrder: false,
    }
  ];

  export const getAllProducts = ()=>{
    return allProducts;
  }