export const allProducts = [
    {
      id: 1,
      name: "Nendoroid Tanjiro Kamado",
      price: 45.99,
      image: "https://goodsmileshop.com/medias/sys_master/images/images/h31/hc4/9254018777118.jpg",
      description: "Figura Nendoroid de Tanjiro Kamado de 'Demon Slayer'. Incluye accesorios y caras intercambiables.",
      stock: 10,
      inStock: true,
      category: "Figuras",
      genre: "Anime",
      preOrder: false,
    },
    {
      id: 2,
      name: "Base para Nendoroid (Transparente)",
      price: 9.99,
      image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/60224/T0uGjtY9aPEJsZxiNAF2DH6bfpW1dV4K.jpg",
      description: "Base de repuesto para Nendoroids. Transparente y compatible con la mayoría de las figuras.",
      stock: 20,
      inStock: true,
      category: "Accesorios",
      genre: "General",
      preOrder: false,
    },
    {
      id: 3,
      name: "Nendoroid Link - Breath of the Wild",
      price: 49.99,
      image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20170126/6213/43479/large/1a05b04bc3e6fa76188061bff89d8010.jpg",
      description: "Figura Nendoroid de Link de 'The Legend of Zelda: Breath of the Wild'. Viene con su arco, espada y escudo.",
      stock: 8,
      inStock: true,
      category: "Figuras",
      genre: "Videojuegos",
      preOrder: false,
    },
    {
      id: 4,
      name: "Nendoroid Miku Hatsune V4X",
      price: 52.99,
      image: "https://imgs2.goodsmileus.com/image/cache/data/productimages/Nendoroids/SakuraMiku_2-0/101_2503061040409105-1200x1200.jpg",
      description: "Figura Nendoroid de Hatsune Miku versión V4X. Incluye micrófono y poses dinámicas.",
      stock: 15,
      inStock: true,
      category: "Figuras",
      genre: "Vocaloid",
      preOrder: false,
    },
    {
      id: 5,
      name: "Set de Rostros Extra para Nendoroids",
      price: 12.99,
      image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/61348/AkMxf7q9JEv063GKWjYSFdcCp5DzLbBN.jpg",
      description: "Pack de rostros adicionales con diferentes gestos para personalizar tu Nendoroid.",
      stock: 30,
      inStock: true,
      category: "Accesorios",
      genre: "General",
      preOrder: false,
    },
    {
      id: 6,
      name: "Nendoroid Gojo Satoru",
      price: 50.99,
      image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20230703/14604/117608/large/5041ff99ab6038f67b91549c5f0e2e0e.jpg",
      description: "Figura Nendoroid de Gojo Satoru de 'Jujutsu Kaisen'. Incluye su máscara y expresiones intercambiables.",
      stock: 5,
      inStock: true,
      category: "Figuras",
      genre: "Anime",
      preOrder: true,
    },
    {
      id: 7,
      name: "Nendoroid Megumin",
      price: 47.99,
      image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20170117/6180/43235/large/013e0c87551bf757a9092070d7634859.jpg",
      description: "Figura Nendoroid de Megumin de 'Konosuba'. Viene con su báculo y efectos de explosión.",
      stock: 0,
      inStock: false,
      category: "Figuras",
      genre: "Anime",
      preOrder: false,
    },
    {
      id: 8,
      name: "Fondo Temático - Noche Estrellada",
      price: 14.99,
      image: "https://www.goodsmile.com/gsc-webrevo-sdk-storage-prd/product/image/product/20220927/13311/104940/large/7ac9a5e3f8810db31f975702069c4a81.jpg",
      description: "Fondo decorativo para exhibir Nendoroids. Tema: Noche estrellada.",
      stock: 12,
      inStock: true,
      category: "Accesorios",
      genre: "General",
      preOrder: false,
    }
  ];

  export const getAllProducts = ()=>{
    return allProducts;
  }